packaging_format = 2

id = "ifm"
name = "IFM"
description.en = "Improved File Manager"
description.fr = "Gestionnaire de fichiers amélioré"

version = "4.0.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://ifmdemo.gitea.de/"
code = "https://github.com/misterunknown/ifm"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifm"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        #[resources.sources.main]
        #url = "https://github.com/misterunknown/ifm/releases/download/v4.0.0/ifm.php"
        #sha256 = "59a888e454a083a420c074e303507e0efd41fb10272f52860c8e6d9cc640aea4"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]

    packages = "php8.0-zip, php8.0-curl, php8.0-mbstring, php8.0-ldap, php8.0-json, php8.0-xml"

