packaging_format = 2

id = "ifm"
name = "IFM"
description.en = "Improved File Manager"
description.fr = "Gestionnaire de fichiers amélioré"

version = "4.0.2~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://ifmdemo.gitea.de/"
code = "https://github.com/misterunknown/ifm"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ifm"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        in_subdir = false
        extract = false
        url = "https://github.com/misterunknown/ifm/releases/download/v4.0.2/ifm.php"
        sha256 = "902e45ef45a5a2c1fc8a1186f1acf3f4588071791e4bc8175de067eb33070594"
        rename = "ifm.php"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]

    packages = "php8.2-zip, php8.2-curl, php8.2-mbstring, php8.2-ldap, php8.2-xml"

